version: '3.7'

services:
  backend:
    image: ehuan2/htn-rabbithole:latest
    ports:
      - 443:443
    command: ["npm", "start"]

  mongo:
    image: mongo:latest
    ports:
      - 8081
    volumes:
      - mongo-data:/mongo-data

volumes:
  mongo-data: