version: '3.7'

services:
  backend:
    image: ehuan2/htn-rabbithole:latest
    ports:
      - 8080:8080
    command: ["npm", "start"]

  redis:
    image: redis:latest
    ports:
      - 6379
    volumes:
      - redis-data:/redis-data

volumes:
  redis-data: