version: '3.7'

services:
  backend:
    image: ehuan2/htn-rabbithole:latest
    ports:
      - 8080:8080
    command: ["npm", "start"]
    env_file: .env

  redis:
    image: redis:latest
    ports:
      - 6379
    volumes:
      - redis-data:/redis-data

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/data
    ports:
      - 5432:5432

volumes:
  db-data:
  redis-data:
